services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: blog-management-server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    environment:
      PORT: 4000
      APP_URL: http://localhost:4000
      DB_URL: mongodb://mongo:27017/Blog_Management_System
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
    command: yarn dev

  mongo:
    image: mongo:7
    container_name: blog-management-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
