/* eslint-disable no-unused-vars */

/**
 * Shared Mongoose schema configuration.
 *
 * - Automatically adds createdAt and updatedAt timestamps
 * - Removes MongoDB version field (__v)
 * - Enables virtual fields in JSON and object transformations
 * - Maps _id to id for API responses
 * - Removes duplicate virtual id generated by Mongoose
 */
const schemaOptions = {
  // automatically manage createdAt and updatedAt fields
  timestamps: true,

  // remove __v field from documents
  versionKey: false,

  // JSON transformation settings
  toJSON: {
    // include virtual fields in JSON output
    virtuals: true,

    // customize serialized response shape
    transform: (_doc, ret) => {
      // extract _id and remove mongoose virtual id
      const { _id, id, ...rest } = ret;

      // expose _id as id
      return { id: _id, ...rest };
    },
  },

  // plain object transformation settings
  toObject: {
    // include virtual fields in object output
    virtuals: true,

    // customize object response shape
    transform: (_doc, ret) => {
      // extract _id and remove mongoose virtual id
      const { _id, id, ...rest } = ret;

      // expose _id as id
      return { id: _id, ...rest };
    },
  },
};

module.exports = schemaOptions;
